//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACNWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int IDFood { get; set; }
        public int IDNguyenLieu { get; set; }
        public string SoLuong { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Material Material { get; set; }
    }
}
