//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACNWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ID { get; set; }
        public Nullable<int> ReaderID { get; set; }
        public Nullable<int> IDFood { get; set; }
        public string Comment { get; set; }
        public string Vote { get; set; }
    
        public virtual User User { get; set; }
    }
}
